### ISSUE TITLE
Remove ToBytes and FromBytes traits

### ISSUE THREAD

**Issue by ValarDragon** [arkworks-rs/algebra#167]
Currently these are a leftover from before `ark-serialize` existed, with a confusing API. People should be using `CanonicalSerialize` instead

**Comment by weikengchen** [comment]
I want to note that sometimes ToBytes and ToBytesGadget are designed to behave the same so that one could compute the Merkle tree of data (via ToBytes[Gadget] to convert it into u8) in the constraint system or outside the constraint system, resulting in the same results.

So removing ToBytes may bring certain challenges for Merkle tree and sponges.

**Comment by ValarDragon** [comment]
The current `ToBytes` trait confusingly only has a `write` method, that doesn't output `Vec<u8>` but instead takes in a custom writer interface that has to be implemented for each type.

I think a `ToBytes` gadget that did what you expected (output `Vec<u8>`, or append the bytes to a standard stream interface of some sort) would be useful

**Comment by Pratyush** [comment]
I think for use cases like Merkle trees and CRHs, we should explicitly just take in bytes and output bytes; conversion into bytes should be the job of the user.

**Comment by weikengchen** [comment]
I agree. It is a little bit weird that `ToBytes` has a slightly more complicated API (Writer, IOError) instead of simply a `to_bytes` function that outputs Vec<u8>, just like `to_bits`.

**Comment by alxiong** [comment]
Consider the plan the team discussed, so... what is the recommended ways to convert all Ark related structs to/from bytes right now? 

using `ark-serialize` instead of the `trait ToBytes` & `to_bytes!()` macro?

**Comment by Pratyush** [comment]
Fixed in #417
