### ISSUE TITLE
panic = "abort" on release

### ISSUE THREAD

**Issue by jon-chuang** [arkworks-rs/algebra#183]
This can reduce binary size and improve instr cache performance. So maybe we should test this.

**Comment by daira** [comment]
It's also completely necessary for security and correctness in mixed-language projects &mdash; because panics across an FFI boundary are undefined behaviour. By their nature it's impossible to prevent panics, and the only other alternative is to add a bunch of verbose and error-prone boilerplate to *all* code that crosses an FFI boundary (including in libraries you don't want to have to change). See also https://github.com/zcash/librustzcash/issues/78 and https://github.com/rust-lang/rust/issues/52652 .

Note that `panic = "abort"` only takes effect for a top-level crate, not dependencies.
