### ISSUE TITLE
Multiscalar multiplication doesn't enforce lengths of input vectors

### ISSUE THREAD

**Issue by gtank** [arkworks-rs/algebra#319]
The variable base `multi_scalar_mul` will silently truncate its inputs if the lengths don't match. This is not usually a desired behavior and would produce incorrect (or at least unexpected) results.

https://github.com/arkworks-rs/algebra/blob/d7fa00e708d76465cc49ed5e33ea42ff17f599b1/ec/src/msm/variable_base.rs#L16-L19

We've run into this a couple of times (https://github.com/celo-org/celo-bls-snark-rs/pull/181, https://github.com/celo-org/celo-bls-snark-rs/pull/222/commits/681cf111cf73459847bacf4378a26ba25a865fcc) and always have to include length checks in the caller code. Instead, the function could return a Result or Option that can express the "unequal inputs" error condition. 

I'm not sure what the preferred idiom for this library would be but I'd be happy to try implementing it if there is one.

**Comment by weikengchen** [comment]
I see. Yes, the code intentionally does the truncation.

Let me ask Pratyush if this implementation is intentional. But I agree that for safety, it is better to fail when it does not match.

@Pratyush

**Comment by Pratyush** [comment]
In downstream usage (eg: the KZG impl in poly-commit), doing that gets cumbersome, because you end up with some variation of `msm(scalars, srs[..scalars.len()])`.

Also, IMO there's a difference between the two cases, stemming from the primary usage of MSMs in commitments:
* when `scalars.len() > group_elements.len()`, the additional scalars get ignored, which means they aren't committed to.
* when `scalars.len() < group_elements.len()`, the additional group elements just get paired with "zero" scalars, and this is still a valid commitment to the original scalars.

Happy to revise this opinion if y'all think that the latter case also has issues.
