### ISSUE TITLE
Move `curves` to `algebra`

### ISSUE THREAD

**Issue by Pratyush** [arkworks-rs/algebra#680]
Integrate `curves` back into `algebra`, in a separate subfolder.

**Comment by z-tech** [comment]
@Pratyush I need some feedback plz. The current hierarchy in curves naturally is:

`workspace` (curves)
- `package` (curve1) 
- `package` (curve2)
...
- `package` (curveN)

I just want to confirm what we expect as the output of this ticket? Each curve will become just a module of this new package "curves" which is part of the workspace "algebra"?

`workspace` (algebra)
- `package` (ff)
...
- `package` (curves)
  - `module` (curve1)
  - `module` (curve2)
...
  - `module` (curveN)

Thanks 😛

**Comment by mmagician** [comment]
This approach will prevent us from publishing each curve independently, right? I would say it is desirable to publish them separately, as then downstream users aren't forced to download and compile all the curves (although this could probably be feature-gated in that scenario).

**Comment by Pratyush** [comment]
`curves` would be it's own workspace, it would just live in the `algebra` repository. So the new layout would be

`workspace` (algebra)
- `package` (ff)
...
- `workspace` (algebra)
  - `package` (curve1)
  - `package` (curve2)
...
  - `package` (curveN)

**Comment by z-tech** [comment]
Hi, to my knowledge workspaces can't be nested in this way: https://stackoverflow.com/questions/49849878/how-to-deal-with-multiple-nested-workspace-roots. If you send me some example of what you want however I could look into it further.

Otherwise, the options I see are:

1) convert `curves` workspace to a package of `algebra` and each curve to a module of that package
2) remove `curves` as a workspace (it will not exist as anything other than a directory) and each curve can be made a package of the workspace `algebra`

**Comment by Pratyush** [comment]
I believe you can put the curves folder under the [exclude](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-members-and-exclude-fields) key

**Comment by z-tech** [comment]
> I believe you can put the curves folder under the [exclude](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-members-and-exclude-fields) key

Ah, so I misunderstood before. You expect no new relation between `algebra` and `curves` They will remain totally different workspaces (like currently) but they'll just share a repo?

**Comment by Pratyush** [comment]
Yup! They'll share the same repo, and follow the directory structure I mentioned above.
