### ISSUE TITLE
SparseMultilinearExtension is very slow in case no evaluation is provided

### ISSUE THREAD

**Issue by anonnice1999** [arkworks-rs/algebra#686]
When I use MLE, I found that if I don't provide any evaluations to the `SparseMultilinearExtension`, the `evaluate()` function will be very slow.

```rust
#[cfg(test)]
pub mod tests {
    use std::time::Instant;

    use ark_ff::{Fp64, MontBackend, MontConfig};
    use ark_poly::{MultilinearExtension, SparseMultilinearExtension};

    #[derive(MontConfig)]
    #[modulus = "389"]
    #[generator = "2"]
    pub struct FrConfig;
    pub type Fp389 = Fp64<MontBackend<FrConfig, 1>>;

    #[test]
    fn circuit_mle_permformance() {
        // A mle of full-zero evaluations, but including two dummy ones.
        let mle = SparseMultilinearExtension::from_evaluations(
            21,
            &[(0, Fp389::from(0)), (1, Fp389::from(0))],
        );

        // A mle of no evaluation.
        let no_evaluations_mle = SparseMultilinearExtension::<Fp389>::from_evaluations(21, &[]);

        let time = Instant::now();
        mle.evaluate(&vec![Fp389::from(1); 21]);
        println!("ESLAPED WITH DUMMY: {:?}", time.elapsed());

        let time = Instant::now();
        no_evaluations_mle.evaluate(&vec![Fp389::from(1); 21]);
        println!("ESLAPED WITH NO EVALUATIONS: {:?}", time.elapsed());
    }
}
``` 

```
Output:
ESLAPED WITH DUMMY: 57.519µs
ESLAPED WITH NO EVALUATIONS: 395.994165ms
```

**Comment by mmagician** [comment]
The example provided is a little contrived in that evaluations of a polynomial with no evaluations on the boolean hypercube are going to be zero no matter the query point. However, the underlying issue is still applicable to polynomials with just one evaluation, which is a little more practical.

The issue is in [`fix_variables`](https://github.com/arkworks-rs/algebra/blob/d106993409c85cb3eaf2ad0c45c7076089c10e7d/poly/src/evaluations/multivariate/multilinear/sparse.rs#L159): we set the window size to the log of `evaluations.len()`, which for 0 or 1 evaluations is going to give us 0. Because of this, the calculation of `focus_length` returns the full query point length, which in turn results in an overly expensive computation of the helper method `precompute_eq`.
