### ISSUE TITLE
Equality for univariate polynomials

### ISSUE THREAD

**Issue by msmirnov18** [arkworks-rs/algebra#709]
Hi everyone! I ran into the following behaviour for univariate polynomials. It seems that by default there is no automation for "combine like terms". For example, the polynomials x + x and 2x are treated as non-equal, if created from coefficients. Here is my code that leads to this:

use ark_ff::fields::{Fp64, MontBackend, MontConfig};
use ark_poly::polynomial::univariate::SparsePolynomial;

#[derive(MontConfig)]
#[modulus = "101"]
#[generator = "2"]
pub struct FieldConfig;
pub type FF = Fp64<MontBackend<FieldConfig, 1>>;

fn main() {
    let p1 = SparsePolynomial::from_coefficients_vec(vec![(1, FF::from(2))]);
    let p2 = SparsePolynomial::from_coefficients_vec(vec![(1, FF::from(1)), (1, FF::from(1))]);
    assert_eq!(p1, p2);
}

Is this the desired behaviour? 

Best, Maxim

**Comment by Antonio95** [comment]
Hi Maxim (nice to see you're exploring Arkworks!). In my opinion, the MWE you present is pathological behaviour. One solution would be to make it clear in the method documentation that such input is not considered (or in API terms: "behaviour ... is undefined"), and leave the code as-is. Another option is to change the code to panic when that situation occurs. Finally, one could group together the coefficients referring to monomials of the same degree. Since sorting by degree happens anyway, the overhead would probably be minimal.

If someone from the Arkworks team makes a decision on this, I'm happy to implement their preferred solution - or even better, let you @msmirnov18 take over and get a contribution in if you are so inclined (or anyone else).

**Comment by mmagician** [comment]
The use case presented is quite rare and as such I'd rather have it documented appropriately than changing how the current behaviour works.

**Comment by msmirnov18** [comment]
I could add some comments to the documentation. Perhaps another remark regarding this behaviour is that it can interfere with other functions. For example, the polynomial x^2 - x^2 + x would have degree 2.

**Comment by mmagician** [comment]
@msmirnov18 just a follow-up, are you still planning to clarify the docs?

**Comment by mmagician** [comment]
Closed in https://github.com/arkworks-rs/algebra/pull/750
