### ISSUE TITLE
Cannot serialize and deserialize group projective elements correctly due to lossy conversion to affine representation

### ISSUE THREAD

**Issue by Saksham010** [arkworks-rs/algebra#861]
use ark_bn254::{Fr as ScalarField, G1Projective as G};

let g_s =  G::generator().mul(ScalarField::from(2)); //Multiplying scalar with generator

//Serialization    
let mut serialized_data = Vec::new();
g_s.serialize_uncompressed(&mut serialized_data).unwrap();

//Deserialization
let deserialized_data= G::deserialize_uncompressed(&*serialized_data).unwrap();

These serialized and deserialized values doesn't match

**Comment by Pratyush** [comment]
Hi! They are not intended to match, but they should be equal (i.e., `assert_eq!(serialized_data, deserialized_data)` should not panic). Can you confirm that this is the case?

**Comment by Saksham010** [comment]
Yes, assertion matches, assertion simply converts project elements to affine and does equality check. It would be useful if serialization and deserialization supported projective elements, especially case for generating proving and verification key files.

**Comment by Pratyush** [comment]
Sorry, the assertion should have been `assert_eq!(g_s, deserialized_data)`. And this assertion does not convert to affine, but does normalize them to enable comparison.

Regardless, this is expected behaviour, as trait is `*Canonical*Serialize`, i.e. the aim is for the serialized data to contain *canonical* representations, which `Projective` elements are not.

Also, I recommend serializing keys in affine form; there is no downside if you do not compress, and it makes MSMs faster.

**Comment by burdges** [comment]
Interestingly, projective coordinates are not even secure as wire representations of elliptic curve points, just purely an internal performance optimization.  See https://eprint.iacr.org/2003/191 or https://crypto.stackexchange.com/questions/83652/what-information-is-revealed-if-we-send-our-points-in-projective-coordinates
